version: '3.3'
services:
  postgres:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: databucket_user
      POSTGRES_PASSWORD: databucket_user
      POSTGRES_DB: databucket

  databucket:
    build: .
    container_name: databucket
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/databucket
      SPRING_DATASOURCE_USERNAME: databucket_user
      SPRING_DATASOURCE_PASSWORD: databucket_user
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: username
      SPRING_MAIL_PASSWORD: password
      SPRING_MAIL_FROM: admin@email.io
