version: '3.3'
services:
  postgres:
    image: postgres:12.2-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: databucket_user
      POSTGRES_PASSWORD: databucket_user
      POSTGRES_DB: databucket

  databucket:
    build: .
    container_name: databucket
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/databucket
      SPRING_DATASOURCE_USERNAME: databucket_user
      SPRING_DATASOURCE_PASSWORD: databucket_user
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: username
      SPRING_MAIL_PASSWORD: password
      SPRING_MAIL_FROM: admin@email.io
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_DOPAUTH_ISSUER-URI: http://auth:8080/auth/realms/databucket

  auth:
    image: quay.io/keycloak/keycloak:12.0.4
    expose:
      - "8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2

  reverse-proxy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    #      - "2015:2015"
    #      - "2019:2019"
    volumes:
      - "${PWD}/docker/Caddyfile:/etc/caddy/Caddyfile"
