version: '3.3'
services:
  postgres:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: databucket_user
      POSTGRES_PASSWORD: databucket_user
      POSTGRES_DB: databucket
