spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        session_factory.interceptor: pl.databucket.server.tenant.EntityInterceptor
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

logging:
  level:
    root: info
    org.springframework.web: error
    org.hibernate: error
    pl.databucket.service.data.DataService: error
    pl.databucket.service.BucketService: error