jwt:
  secret: SGVsbG9Yb3JsZFRoaXNJc015U2VjcmV0S2V5Rm9xSldUVG9rZW5zMTIzNDU2Nzg5MA==
  secret.legacy: veryverysecret
  expire.hours: 24

server:
  port: 8080
  servlet.context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/databucket
    username: databucket_user
    password: databucket_user
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    from: admin@email.io
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
