
export const iconsNames = [
    'home',
    'settings',
    // 'done',
    // 'account_circle',
    'check_circle',
    'face',
    'info',
    'fingerprint',
    'delete',
    'favorite',
    'shopping_cart',
    'visibility',
    'logout',
    'favorite_border',
    'description',
    'help_outline',
    'language',
    'lock',
    'schedule',
    'thumb_up',
    'verified',
    'lightbulb',
    'event',
    'dashboard',
    'list',
    'filter_alt',
    'calendar_today',
    'trending_up',
    'login',
    'account_balance',
    'question_answer',
    'visibility_off',
    'open_in_new',
    'check_circle_outline',
    'paid',
    'shopping_bag',
    'date_range',
    'help',
    'highlight_off',
    'android',
    'arrow_right_alt',
    'task_alt',
    'article',
    'pets',
    'star_rate',
    'build',
    'credit_card',
    'perm_identity',
    'flutter_dash',
    'verified_user',
    'history',
    'fact_check',
    'assignment',
    'analytics',
    'delete_outline',
    'report_problem',
    'work',
    'accessibility',
    'code',
    'savings',
    'autorenew',
    'print',
    'add_shopping_cart',
    'account_balance_wallet',
    'today',
    'grade',
    'view_list',
    'delete_forever',
    'store',
    'lock_open',
    'admin_panel_settings',
    'room',
    'watch_later',
    'power_settings_new',
    'explore',
    'update',
    'launch',
    'bug_report',
    'pan_tool',
    'done_outline',
    '3d_rotation',
    'done_all',
    'thumb_up_off_alt',
    'view_in_ar',
    'receipt',
    'account_box',
    'contact_support',
    'bookmark',
    'shopping_basket',
    'feedback',
    'touch_app',
    // 'accessibility_new',
    'timeline',
    'note_add',
    'supervisor_account',
    'reorder',
    'payment',
    'zoom_in',
    'bookmark_border',
    'drag_indicator',
    'assessment',
    'flight_takeoff',
    'add_task',
    'exit_to_app',
    'leaderboard',
    'stars',
    'open_in_full',
    'pending',
    'pending_actions',
    'preview',
    'alarm',
    'dns',
    'work_outline',
    'gavel',
    'nightlight_round',
    'assignment_ind',
    'record_voice_over',
    'cached',
    'published_with_changes',
    'card_giftcard',
    'book',
    'supervised_user_circle',
    'get_app',
    'extension',
    'assignment_turned_in',
    'label',
    'swap_horiz',
    'translate',
    'contact_page',
    'thumb_down',
    'sync_alt',
    'trending_flat',
    'privacy_tip',
    'minimize',
    'group_work',
    'hourglass_empty',
    'help_center',
    'loyalty',
    'announcement',
    'space_dashboard',
    'euro_symbol',
    'dashboard_customize',
    'rule',
    // 'settings_applications',
    'api',
    'grading',
    'arrow_circle_up',
    'sticky_note_2',
    'sensors',
    'support',
    'compare_arrows',
    'source',
    'copyright',
    'close_fullscreen',
    'query_builder',
    'input',
    'book_online',
    'track_changes',
    'backup',
    'view_headline',
    'g_translate',
    'subject',
    'settings_phone',
    'restore',
    'edit_calendar',
    'find_in_page',
    'build_circle',
    'table_view',
    'bookmarks',
    'dangerous',
    'redeem',
    'model_training',
    'perm_media',
    'https',
    'open_with',
    'swap_vert',
    'arrow_circle_down',
    'swipe',
    // 'accessible',
    'circle_notifications',
    'trending_down',
    'pageview',
    'label_important',
    'zoom_out',
    'invert_colors',
    'toc',
    'disabled_by_default',
    'wysiwyg',
    // 'settings_accessibility',
    'perm_phone_msg',
    'integration_instructions',
    'file_present',
    'card_membership',
    'speaker_notes',
    'change_history',
    'thumbs_up_down',
    'offline_bolt',
    'view_module',
    'perm_contact_calendar',
    'bookmark_add',
    'ads_click',
    'opacity',
    'upgrade',
    'alarm_on',
    'calendar_view_month',
    'production_quantity_limits',
    'donut_large',
    'add_to_drive',
    'no_accounts',
    'expand',
    'saved_search',
    'aspect_ratio',
    'mediation',
    'accessible_forward',
    'commute',
    'settings_ethernet',
    'theaters',
    'class',
    'thumb_down_off_alt',
    'important_devices',
    'settings_backup_restore',
    'schedule_send',
    'maximize',
    'youtube_searched_for',
    'segment',
    'addchart',
    'not_started',
    'anchor',
    'bookmark_added',
    'system_update_alt',
    'flaky',
    'mark_as_unread',
    'contactless',
    'settings_input_antenna',
    'open_in_browser',
    'turned_in',
    'history_toggle_off',
    'view_column',
    'fit_screen',
    'settings_voice',
    'tour',
    'view_week',
    'pregnant_woman',
    'flight_land',
    'shop',
    'unpublished',
    'view_agenda',
    'view_carousel',
    'camera_enhance',
    'settings_remote',
    'highlight_alt',
    'tab',
    'search_off',
    'offline_pin',
    'toll',
    'hourglass_full',
    'lock_clock',
    'assignment_late',
    'hide_source',
    'online_prediction',
    'settings_input_component',
    'next_plan',
    'turned_in_not',
    'donut_small',
    'remove_shopping_cart',
    'all_inbox',
    'dynamic_form',
    'plagiarism',
    'outlet',
    'event_seat',
    'rowing',
    'view_sidebar',
    'edit_off',
    'markunread_mailbox',
    'settings_power',
    'try',
    'gif',
    'restore_from_trash',
    'swap_horizontal_circle',
    'settings_input_composite',
    'smart_button',
    'alarm_add',
    'request_page',
    'assignment_return',
    'play_for_work',
    'card_travel',
    // 'settings_overscan',
    'compress',
    // 'settings_bluetooth',
    'polymer',
    // 'wifi_protected_setup',
    'view_quilt',
    'outbox',
    // 'vertical_split',
    // 'settings_brightness',
    // 'calendar_view_week',
    // 'http',
    // 'find_replace',
    // 'spellcheck',
    // 'remove_done',
    // 'chrome_reader_mode',
    // 'calendar_view_day',
    // 'quickreply',
    // 'settings_cell',
    // 'view_day',
    // 'comment_bank',
    // 'batch_prediction',
    // 'outbound',
    // 'picture_in_picture',
    // 'new_label',
    // 'hotel_class',
    // 'tips_and_updates',
    // 'view_stream',
    // 'restore_page',
    // 'code_off',
    // 'bookmark_remove',
    // 'send_and_archive',
    // 'credit_card_off',
    // 'settings_input_hdmi',
    // 'backup_table',
    // 'assignment_returned',
    // 'alarm_off',
    // 'line_weight',
    // 'line_style',
    // 'perm_scan_wifi',
    // 'swap_vertical_circle',
    // 'app_blocking',
    // 'flip_to_front',
    // 'cancel_schedule_send',
    // 'eject',
    // 'perm_data_setting',
    // 'speaker_notes_off',
    // 'sensors_off',
    // 'horizontal_split',
    // 'shop_two',
    // 'generating_tokens',
    // 'perm_device_information',
    // 'settings_input_svideo',
    // 'hourglass_disabled',
    // 'picture_in_picture_alt',
    // 'open_in_new_off',
    // 'voice_over_off',
    // 'update_disabled',
    // 'work_off',
    // 'subtitles_off',
    // 'view_array',
    // 'all_out',
    // 'tab_unselected',
    // 'data_exploration',
    // 'free_cancellation',
    // 'flip_to_back',
    // 'shop_2',
    // 'label_off',
    // 'explore_off',
    // 'text_rotation_none',
    // 'perm_camera_mic',
    // 'rounded_corner',
    // 'not_accessible',
    // 'private_connectivity',
    // 'disabled_visible',
    // 'text_rotate_vertical',
    // 'extension_off',
    // 'text_rotation_angleup',
    // 'pin_invoke',
    // 'text_rotation_down',
    // 'text_rotation_angledown',
    // 'text_rotate_up',
    // 'pin_end',
    // 'menu',
    // 'close',
    // 'expand_more',
    // 'arrow_back',
    // 'chevron_right',
    // 'arrow_forward_ios',
    // 'arrow_back_ios',
    // 'arrow_drop_down',
    // 'cancel',
    // 'more_vert',
    // 'arrow_forward',
    // 'expand_less',
    // 'more_horiz',
    // 'chevron_left',
    // 'check',
    // 'refresh',
    // 'apps',
    // 'arrow_back_ios_new',
    // 'arrow_upward',
    // 'payments',
    // 'east',
    // 'campaign',
    // 'arrow_right',
    // 'menu_open',
    // 'arrow_downward',
    // 'double_arrow',
    // 'fullscreen',
    // 'unfold_more',
    // 'maps_home_work',
    // 'arrow_drop_up',
    // 'west',
    // 'south',
    // 'arrow_left',
    // 'arrow_drop_down_circle',
    // 'home_work',
    // 'first_page',
    // 'fullscreen_exit',
    // 'north',
    // 'north_east',
    // 'last_page',
    // 'subdirectory_arrow_right',
    // 'unfold_less',
    // 'legend_toggle',
    // 'assistant_direction',
    // 'app_settings_alt',
    // 'subdirectory_arrow_left',
    // 'south_east',
    // 'waterfall_chart',
    // 'north_west',
    // 'switch_left',
    // 'south_west',
    // 'switch_right',
    // 'pivot_table_chart',
    // 'offline_share',
    // 'person',
    // 'facebook',
    // 'notifications',
    // 'groups',
    // 'share',
    // 'people',
    // 'school',
    // 'person_outline',
    // 'public',
    // 'emoji_events',
    // 'person_add',
    // 'group',
    // 'engineering',
    // 'notifications_active',
    // 'construction',
    // 'psychology',
    // 'people_alt',
    // 'health_and_safety',
    // 'coronavirus',
    // 'emoji_emotions',
    // 'travel_explore',
    // 'group_add',
    // 'notifications_none',
    // 'sentiment_satisfied',
    // 'thumb_up_alt',
    // 'emoji_objects',
    // 'sentiment_very_satisfied',
    // 'precision_manufacturing',
    // 'science',
    // 'military_tech',
    // 'sports_esports',
    // 'ios_share',
    // 'location_city',
    // 'cake',
    // 'person_add_alt',
    // 'sentiment_dissatisfied',
    // 'self_improvement',
    // 'history_edu',
    // 'emoji_people',
    // 'catching_pokemon',
    // 'sentiment_very_dissatisfied',
    // 'mood',
    // 'female',
    // 'recommend',
    // 'poll',
    // 'masks',
    // 'domain',
    // 'person_remove',
    // 'male',
    // 'sports_soccer',
    // 'whatshot',
    // 'people_outline',
    // 'connect_without_contact',
    // 'hiking',
    // 'person_add_alt_1',
    // 'sentiment_neutral',
    // 'architecture',
    // 'person_off',
    // 'emoji_nature',
    // 'notifications_off',
    // 'emoji_symbols',
    // 'mood_bad',
    // 'switch_account',
    // 'nights_stay',
    // 'luggage',
    // 'recycling',
    // 'sports_kabaddi',
    // 'notification_add',
    // 'thumb_down_alt',
    // 'sports_basketball',
    // 'back_hand',
    // 'emoji_flags',
    // 'social_distance',
    // 'waving_hand',
    // 'water_drop',
    // 'king_bed',
    // 'emoji_food_beverage',
    // 'front_hand',
    // 'sick',
    // 'sports_tennis',
    // 'clean_hands',
    // 'outdoor_grill',
    // 'deck',
    // 'sports',
    // 'emoji_transportation',
    // 'plus_one',
    // 'transgender',
    // 'sanitizer',
    // 'elderly',
    // 'reduce_capacity',
    // 'fireplace',
    // 'sports_baseball',
    // 'add_reaction',
    // 'follow_the_signs',
    // 'sports_motorsports',
    // 'add_moderator',
    // 'edit_notifications',
    // 'real_estate_agent',
    // 'kayaking',
    // 'sports_volleyball',
    // 'sports_football',
    // 'sports_handball',
    // 'surfing',
    // 'piano',
    // '6_ft_apart',
    // 'skateboarding',
    // 'downhill_skiing',
    // 'pages',
    // 'single_bed',
    // 'public_off',
    // 'remove_moderator',
    // 'personal_injury',
    // 'nordic_walking',
    // 'sports_cricket',
    // 'safety_divider',
    // 'paragliding',
    // 'person_remove_alt_1',
    // 'snowboarding',
    // 'sports_mma',
    // 'notifications_paused',
    // 'party_mode',
    // 'compost',
    // 'sports_golf',
    // 'kitesurfing',
    // 'sports_rugby',
    // 'group_off',
    // 'ice_skating',
    // 'snowshoeing',
    // 'sports_hockey',
    // 'sledding',
    // 'cruelty_free',
    // 'piano_off',
    // 'no_luggage',
    // 'add',
    // 'add_circle_outline',
    // 'add_circle',
    // 'send',
    // 'content_copy',
    // 'clear',
    // 'save',
    // 'link',
    // 'mail',
    // 'filter_list',
    // 'remove',
    // 'inventory_2',
    // 'insights',
    // 'create',
    // 'bolt',
    // 'remove_circle_outline',
    // 'inventory',
    // 'sort',
    // 'remove_circle',
    // 'flag',
    // 'add_box',
    // 'push_pin',
    // 'reply',
    // 'block',
    // 'calculate',
    // 'content_paste',
    // 'how_to_reg',
    // 'undo',
    // 'file_copy',
    // 'report',
    // 'shield',
    // 'archive',
    // 'save_alt',
    // 'backspace',
    // 'policy',
    // 'change_circle',
    // 'tag',
    // 'content_cut',
    // 'forward',
    // 'redo',
    // 'inbox',
    // 'biotech',
    // 'stacked_bar_chart',
    // 'drafts',
    // 'ballot',
    // 'outlined_flag',
    // 'link_off',
    // 'markunread',
    // 'stream',
    // 'square_foot',
    // 'delete_sweep',
    // 'report_gmailerrorred',
    // 'dynamic_feed',
    // 'waves',
    // 'add_link',
    // 'where_to_vote',
    // 'move_to_inbox',
    // 'copy_all',
    // 'reply_all',
    // 'unarchive',
    // 'low_priority',
    // 'how_to_vote',
    // 'text_format',
    // 'weekend',
    // 'select_all',
    // 'upcoming',
    // 'gesture',
    // 'font_download',
    // 'attribution',
    // 'next_week',
    // 'content_paste_off',
    // 'report_off',
    // 'font_download_off',
    // 'email',
    // 'location_on',
    // 'call',
    // 'phone',
    // 'business',
    // 'chat',
    // 'mail_outline',
    // 'vpn_key',
    // 'list_alt',
    // 'qr_code_scanner',
    // 'chat_bubble_outline',
    // 'alternate_email',
    // 'chat_bubble',
    // 'forum',
    // 'textsms',
    // 'sentiment_satisfied_alt',
    // 'qr_code_2',
    // 'contact_mail',
    // 'person_search',
    // 'message',
    // 'qr_code',
    // 'contacts',
    // 'comment',
    // 'app_registration',
    // 'live_help',
    // 'rss_feed',
    // 'contact_phone',
    // 'import_contacts',
    // 'import_export',
    // 'forward_to_inbox',
    // 'hourglass_bottom',
    // 'mark_email_read',
    // 'hourglass_top',
    // 'read_more',
    // 'call_end',
    // 'document_scanner',
    // 'mark_email_unread',
    // 'more_time',
    // 'dialpad',
    // 'clear_all',
    // 'phone_enabled',
    // 'mark_chat_unread',
    // 'screen_share',
    // '3p',
    // 'present_to_all',
    // 'cancel_presentation',
    // 'stay_current_portrait',
    // 'unsubscribe',
    // 'call_made',
    // 'mark_chat_read',
    // 'call_split',
    // 'phonelink_ring',
    // 'duo',
    // 'domain_verification',
    // 'phonelink_lock',
    // 'stay_primary_portrait',
    // 'add_ic_call',
    // 'location_off',
    // 'ring_volume',
    // 'phone_disabled',
    // 'swap_calls',
    // 'phonelink_setup',
    // 'mobile_screen_share',
    // 'call_received',
    // 'cell_wifi',
    // 'call_merge',
    // 'speaker_phone',
    // 'voicemail',
    // 'person_add_disabled',
    // 'domain_disabled',
    // 'call_missed_outgoing',
    // 'portable_wifi_off',
    // 'call_missed',
    // 'phonelink_erase',
    // 'desktop_access_disabled',
    // 'rtt',
    // 'pause_presentation',
    // 'sip',
    // 'stop_screen_share',
    // 'stay_current_landscape',
    // 'invert_colors_off',
    // 'wifi_calling',
    // 'nat',
    // 'dialer_sip',
    // 'print_disabled',
    // 'stay_primary_landscape',
    // 'no_sim',
    // 'edit',
    // 'navigate_next',
    // 'photo_camera',
    // 'image',
    // 'picture_as_pdf',
    // 'tune',
    // 'circle',
    // 'receipt_long',
    // 'timer',
    // 'auto_stories',
    // 'auto_awesome',
    // 'navigate_before',
    // 'add_a_photo',
    // 'palette',
    // 'collections',
    // 'remove_red_eye',
    // 'music_note',
    // 'wb_sunny',
    // 'brush',
    // 'add_photo_alternate',
    // 'flash_on',
    // 'auto_fix_high',
    // 'camera_alt',
    // 'euro',
    // 'audiotrack',
    // 'camera',
    // 'looks_one',
    // 'style',
    // 'control_point',
    // 'straighten',
    // 'photo_library',
    // 'portrait',
    // 'color_lens',
    // 'adjust',
    // 'landscape',
    // 'grid_on',
    // 'video_camera_front',
    // 'filter_vintage',
    // 'image_search',
    // 'blur_on',
    // 'crop_square',
    // 'timelapse',
    // 'slideshow',
    // 'collections_bookmark',
    // 'rotate_right',
    // 'lens',
    // 'panorama_fish_eye',
    // 'filter_drama',
    // 'auto_awesome_motion',
    // 'looks_two',
    // 'healing',
    // 'crop',
    // 'crop_free',
    // 'wb_incandescent',
    // 'tag_faces',
    // 'looks_3',
    // 'dehaze',
    // 'rotate_left',
    // 'broken_image',
    // 'nature_people',
    // 'face_retouching_natural',
    // 'assistant',
    // 'colorize',
    // 'auto_awesome_mosaic',
    // 'center_focus_strong',
    // 'wb_cloudy',
    // 'brightness_4',
    // 'photo',
    // 'flare',
    // 'brightness_5',
    // 'crop_original',
    // 'compare',
    // 'cases',
    // 'grain',
    // 'flash_off',
    // 'filter_none',
    // 'brightness_6',
    // 'flip_camera_android',
    // 'filter_center_focus',
    // 'movie_creation',
    // 'details',
    // 'brightness_1',
    // 'loupe',
    // 'nature',
    // 'texture',
    // 'filter_1',
    // 'animation',
    // 'brightness_7',
    // 'flip_camera_ios',
    // 'panorama',
    // 'looks_4',
    // 'add_to_photos',
    // 'image_not_supported',
    // 'flip',
    // 'auto_fix_normal',
    // 'bedtime',
    // 'photo_size_select_actual',
    // 'view_comfy',
    // 'leak_add',
    // 'transform',
    // 'motion_photos_on',
    // 'timer_off',
    // 'filter',
    // 'center_focus_weak',
    // 'crop_din',
    // 'video_camera_back',
    // 'movie_filter',
    // 'shutter_speed',
    // 'photo_camera_front',
    // 'gradient',
    // 'control_point_duplicate',
    // 'mic_external_on',
    // 'thermostat_auto',
    // 'filter_tilt_shift',
    // 'music_off',
    // 'looks_5',
    // 'rotate_90_degrees_ccw',
    // 'photo_album',
    // 'view_compact',
    // 'filter_2',
    // 'assistant_photo',
    // 'motion_photos_auto',
    // 'photo_filter',
    // 'blur_circular',
    // 'exposure_plus_1',
    // 'hdr_strong',
    // 'hide_image',
    // 'looks_6',
    // 'looks',
    // 'vrpano',
    // 'brightness_3',
    // 'crop_7_5',
    // 'iso',
    // 'crop_rotate',
    // 'crop_16_9',
    // 'camera_front',
    // 'flash_auto',
    // 'filter_hdr',
    // 'wb_twilight',
    // 'camera_roll',
    // 'tonality',
    // 'brightness_2',
    // 'exposure',
    // 'filter_frames',
    // 'photo_size_select_small',
    // 'filter_3',
    // 'blur_linear',
    // 'burst_mode',
    // 'linked_camera',
    // 'hdr_weak',
    // 'photo_size_select_large',
    // 'crop_3_2',
    // 'crop_portrait',
    // 'monochrome_photos',
    // 'crop_5_4',
    // 'filter_b_and_w',
    // 'crop_landscape',
    // 'grid_off',
    // 'photo_camera_back',
    // '24mp',
    // 'switch_camera',
    // 'face_retouching_off',
    // 'switch_video',
    // 'filter_5',
    // 'motion_photos_paused',
    // 'video_stable',
    // 'leak_remove',
    // 'motion_photos_off',
    // 'timer_3',
    // 'auto_fix_off',
    // 'filter_7',
    // 'exposure_plus_2',
    // 'filter_4',
    // 'exposure_zero',
    // 'wb_shade',
    // 'blur_off',
    // 'camera_rear',
    // 'raw_on',
    // 'panorama_wide_angle_select',
    // 'hdr_on',
    // 'filter_6',
    // 'dirty_lens',
    // 'filter_9',
    // 'filter_9_plus',
    // 'panorama_photosphere',
    // 'wb_iridescent',
    // 'exposure_neg_2',
    // 'vignette',
    // 'panorama_horizontal_select',
    // 'motion_photos_pause',
    // 'timer_10',
    // '30fps_select',
    // 'exposure_neg_1',
    // 'panorama_horizontal',
    // 'image_aspect_ratio',
    // '23mp',
    // 'filter_8',
    // 'incomplete_circle',
    // '60fps_select',
    // 'panorama_photosphere_select',
    // 'panorama_vertical_select',
    // 'mic_external_off',
    // '6mp',
    // 'panorama_wide_angle',
    // '12mp',
    // 'hdr_plus',
    // 'hdr_enhanced_select',
    // 'autofps_select',
    // 'wb_auto',
    // '13mp',
    // '20mp',
    // 'hdr_off',
    // 'mp',
    // 'panorama_vertical',
    // '10mp',
    // '11mp',
    // '21mp',
    // 'hevc',
    // '18mp',
    // '19mp',
    // '22mp',
    // '3mp',
    // '15mp',
    // '16mp',
    // '8mp',
    // '14mp',
    // 'raw_off',
    // '4mp',
    // '9mp',
    // '17mp',
    // '2mp',
    // '7mp',
    // '5mp',
    // 'local_shipping',
    // 'place',
    // 'menu_book',
    // 'local_offer',
    // 'map',
    // 'category',
    // 'directions_car',
    // 'restaurant',
    // 'badge',
    // 'volunteer_activism',
    // 'local_fire_department',
    // 'my_location',
    // 'directions_run',
    // 'flight',
    // 'handyman',
    // 'near_me',
    // 'local_mall',
    // 'restaurant_menu',
    // 'medical_services',
    // 'directions_walk',
    // 'park',
    // 'layers',
    // 'local_hospital',
    // 'pin_drop',
    // 'local_cafe',
    // 'local_library',
    // 'directions_bike',
    // 'lunch_dining',
    // 'design_services',
    // 'celebration',
    // 'local_atm',
    // 'directions_car_filled',
    // 'miscellaneous_services',
    // 'local_grocery_store',
    // 'person_pin',
    // 'rate_review',
    // 'delivery_dining',
    // 'local_activity',
    // 'local_phone',
    // 'home_repair_service',
    // 'fastfood',
    // 'zoom_out_map',
    // 'directions_bus',
    // 'local_florist',
    // 'local_police',
    // 'person_pin_circle',
    // 'hotel',
    // 'local_parking',
    // 'navigation',
    // 'cleaning_services',
    // 'local_post_office',
    // 'train',
    // 'money',
    // 'local_gas_station',
    // 'directions',
    // 'traffic',
    // 'pedal_bike',
    // 'alt_route',
    // 'electrical_services',
    // 'local_bar',
    // 'two_wheeler',
    // 'agriculture',
    // '360',
    // 'directions_boat',
    // 'liquor',
    // 'beenhere',
    // 'local_airport',
    // 'moving',
    // 'local_dining',
    // 'local_drink',
    // 'add_business',
    // 'sailing',
    // 'ramen_dining',
    // 'add_location_alt',
    // 'local_taxi',
    // 'wine_bar',
    // 'hail',
    // 'local_pizza',
    // 'maps_ugc',
    // 'dinner_dining',
    // 'local_laundry_service',
    // 'theater_comedy',
    // 'not_listed_location',
    // 'add_location',
    // 'local_printshop',
    // 'trip_origin',
    // 'bakery_dining',
    // 'terrain',
    // 'directions_bus_filled',
    // 'icecream',
    // 'local_pharmacy',
    // 'transfer_within_a_station',
    // 'store_mall_directory',
    // 'multiple_stop',
    // 'museum',
    // 'nightlife',
    // 'set_meal',
    // 'car_rental',
    // 'takeout_dining',
    // 'edit_road',
    // 'local_see',
    // 'plumbing',
    // 'edit_location',
    // 'hardware',
    // 'ev_station',
    // 'emergency',
    // 'pest_control',
    // 'electric_car',
    // 'directions_boat_filled',
    // 'run_circle',
    // 'festival',
    // 'satellite',
    // 'local_convenience_store',
    // 'add_road',
    // 'edit_location_alt',
    // 'layers_clear',
    // 'dry_cleaning',
    // 'departure_board',
    // 'moped',
    // 'tram',
    // 'breakfast_dining',
    // 'attractions',
    // 'wrong_location',
    // 'car_repair',
    // 'edit_attributes',
    // 'brunch_dining',
    // 'local_movies',
    // 'directions_transit',
    // 'atm',
    // 'taxi_alert',
    // 'subway',
    // 'electric_scooter',
    // 'electric_bike',
    // 'local_car_wash',
    // 'hvac',
    // 'transit_enterexit',
    // 'local_hotel',
    // 'bus_alert',
    // 'streetview',
    // 'compass_calibration',
    // 'directions_subway',
    // 'electric_moped',
    // 'directions_railway',
    // 'no_meals',
    // 'electric_rickshaw',
    // 'railway_alert',
    // 'local_play',
    // 'pest_control_rodent',
    // 'bike_scooter',
    // 'directions_transit_filled',
    // 'snowmobile',
    // 'near_me_disabled',
    // 'directions_subway_filled',
    // 'directions_railway_filled',
    // 'no_transfer',
    // 'file_download',
    // 'file_upload',
    // 'download',
    // 'folder',
    // 'grid_view',
    // 'upload_file',
    // 'cloud',
    // 'cloud_upload',
    // 'folder_open',
    // 'text_snippet',
    // 'cloud_download',
    // 'request_quote',
    // 'attachment',
    // 'upload',
    // 'drive_file_rename_outline',
    // 'download_for_offline',
    // 'create_new_folder',
    // 'downloading',
    // 'folder_shared',
    // 'cloud_done',
    // 'topic',
    // 'workspaces',
    // 'cloud_queue',
    // 'download_done',
    // 'cloud_off',
    // 'approval',
    // 'drive_folder_upload',
    // 'drive_file_move',
    // 'file_download_done',
    // 'attach_email',
    // 'rule_folder',
    // 'cloud_circle',
    // 'snippet_folder',
    // 'file_download_off',
    // 'drive_file_move_rtl',
    // 'play_arrow',
    // 'play_circle_filled',
    // 'videocam',
    // 'play_circle',
    // 'volume_up',
    // 'mic',
    // 'play_circle_outline',
    // 'pause',
    // 'volume_off',
    // 'library_books',
    // 'replay',
    // 'stop',
    // 'speed',
    // 'skip_next',
    // 'movie',
    // 'new_releases',
    // 'skip_previous',
    // 'fiber_manual_record',
    // 'fast_forward',
    // 'playlist_add',
    // 'equalizer',
    // 'web',
    // 'loop',
    // 'volume_mute',
    // 'mic_off',
    // 'video_library',
    // 'pause_circle',
    // 'playlist_add_check',
    // 'library_add',
    // 'video_call',
    // 'stop_circle',
    // 'repeat',
    // 'mic_none',
    // 'subscriptions',
    // 'library_music',
    // 'shuffle',
    // 'sort_by_alpha',
    // 'fast_rewind',
    // 'videocam_off',
    // 'hearing',
    // 'not_interested',
    // 'pause_circle_filled',
    // 'album',
    // 'volume_down',
    // 'radio',
    // 'fiber_new',
    // 'subtitles',
    // 'recent_actors',
    // 'queue_music',
    // 'games',
    // 'library_add_check',
    // 'av_timer',
    // 'web_asset',
    // 'note',
    // 'pause_circle_outline',
    // 'branding_watermark',
    // 'forward_10',
    // 'queue',
    // 'replay_10',
    // 'playlist_play',
    // 'closed_caption',
    // 'replay_circle_filled',
    // 'video_settings',
    // 'closed_caption_off',
    // 'featured_play_list',
    // 'control_camera',
    // '5g',
    // 'slow_motion_video',
    // 'add_to_queue',
    // 'replay_30',
    // 'airplay',
    // 'repeat_on',
    // 'high_quality',
    // 'hd',
    // 'shuffle_on',
    // 'music_video',
    // 'call_to_action',
    // 'forward_30',
    // 'hearing_disabled',
    // 'repeat_one',
    // 'featured_video',
    // 'snooze',
    // 'replay_5',
    // 'forward_5',
    // 'art_track',
    // '4k',
    // 'queue_play_next',
    // 'video_label',
    // 'explicit',
    // 'surround_sound',
    // 'remove_from_queue',
    // 'closed_caption_disabled',
    // 'repeat_one_on',
    // 'fiber_smart_record',
    // '10k',
    // 'web_asset_off',
    // 'play_disabled',
    // 'missed_video_call',
    // 'sd',
    // '2k',
    // '4k_plus',
    // '1k',
    // '8k',
    // '5k_plus',
    // '6k_plus',
    // '8k_plus',
    // '9k_plus',
    // '5k',
    // 'fiber_dvr',
    // 'fiber_pin',
    // '1k_plus',
    // '6k',
    // '7k_plus',
    // '9k',
    // '3k_plus',
    // '2k_plus',
    // '3k',
    // '7k',
    // 'star',
    // 'check_box',
    // 'check_box_outline_blank',
    // 'radio_button_unchecked',
    // 'radio_button_checked',
    // 'toggle_on',
    // 'star_border',
    // 'toggle_off',
    // 'star_outline',
    // 'star_half',
    // 'indeterminate_check_box',
    // 'star_purple500',
    // 'star_border_purple500',
    // 'warning',
    // 'error',
    // 'error_outline',
    // 'warning_amber',
    // 'notification_important',
    // 'add_alert',
    // 'auto_delete',
    // 'attach_money',
    // 'format_list_bulleted',
    // 'mode_edit',
    // 'monetization_on',
    // 'attach_file',
    // 'post_add',
    // 'bar_chart',
    // 'insert_photo',
    // 'edit_note',
    // 'insert_drive_file',
    // 'format_quote',
    // 'drag_handle',
    // 'checklist',
    // 'show_chart',
    // 'format_list_numbered',
    // 'table_chart',
    // 'border_color',
    // 'insert_emoticon',
    // 'mode',
    // 'notes',
    // 'pie_chart',
    // 'auto_graph',
    // 'text_fields',
    // 'table_rows',
    // 'query_stats',
    // 'format_bold',
    // 'mode_edit_outline',
    // 'insert_chart_outlined',
    // 'publish',
    // 'title',
    // 'mode_comment',
    // 'insert_link',
    // 'insert_invitation',
    // 'checklist_rtl',
    // 'functions',
    // 'format_size',
    // 'format_color_fill',
    // 'linear_scale',
    // 'insert_chart',
    // 'draw',
    // 'bubble_chart',
    // 'format_align_left',
    // 'format_italic',
    // 'add_comment',
    // 'stacked_line_chart',
    // 'insert_comment',
    // 'money_off',
    // 'vertical_align_bottom',
    // 'horizontal_rule',
    // 'format_underlined',
    // 'vertical_align_top',
    // 'format_paint',
    // 'height',
    // 'format_align_center',
    // 'merge_type',
    // 'format_list_numbered_rtl',
    // 'schema',
    // 'format_color_text',
    // 'scatter_plot',
    // 'highlight',
    // 'add_chart',
    // 'format_align_right',
    // 'format_shapes',
    // 'format_align_justify',
    // 'money_off_csred',
    // 'format_color_reset',
    // 'align_horizontal_left',
    // 'pie_chart_outline',
    // 'short_text',
    // 'multiline_chart',
    // 'format_indent_increase',
    // 'vertical_align_center',
    // 'border_all',
    // 'strikethrough_s',
    // 'score',
    // 'area_chart',
    // 'format_line_spacing',
    // 'horizontal_distribute',
    // 'space_bar',
    // 'format_indent_decrease',
    // 'vertical_distribute',
    // 'format_strikethrough',
    // 'align_vertical_bottom',
    // 'align_horizontal_right',
    // 'margin',
    // 'align_horizontal_center',
    // 'format_clear',
    // 'align_vertical_center',
    // 'superscript',
    // 'align_vertical_top',
    // 'subscript',
    // 'border_clear',
    // 'border_outer',
    // 'wrap_text',
    // 'padding',
    // 'border_style',
    // 'border_bottom',
    // 'format_textdirection_l_to_r',
    // 'border_inner',
    // 'border_vertical',
    // 'format_textdirection_r_to_l',
    // 'border_horizontal',
    // 'border_top',
    // 'border_right',
    // 'border_left',
    // 'support_agent',
    // 'wifi',
    // 'account_tree',
    // 'phone_in_talk',
    // 'event_available',
    // 'priority_high',
    // 'sync',
    // 'event_note',
    // 'sms',
    // 'confirmation_number',
    // 'live_tv',
    // 'ondemand_video',
    // 'wc',
    // 'do_not_disturb_on',
    // 'wifi_off',
    // 'drive_eta',
    // 'more',
    // 'do_not_disturb',
    // 'event_busy',
    // 'power',
    // 'do_disturb_on',
    // 'vpn_lock',
    // 'time_to_leave',
    // 'folder_special',
    // 'enhanced_encryption',
    // 'sync_problem',
    // 'running_with_errors',
    // 'network_check',
    // 'do_disturb',
    // 'system_update',
    // 'adb',
    // 'voice_chat',
    // 'phone_callback',
    // 'power_off',
    // 'sms_failed',
    // 'phone_forwarded',
    // 'personal_video',
    // 'vibration',
    // 'airline_seat_recline_normal',
    // 'do_disturb_alt',
    // 'do_not_disturb_alt',
    // 'no_encryption',
    // 'sync_disabled',
    // 'sd_card',
    // 'phone_missed',
    // 'tap_and_play',
    // 'imagesearch_roller',
    // 'airline_seat_recline_extra',
    // 'mms',
    // 'disc_full',
    // 'bluetooth_audio',
    // 'no_encryption_gmailerrorred',
    // 'phone_paused',
    // 'airline_seat_individual_suite',
    // 'do_not_disturb_off',
    // 'network_locked',
    // 'sd_card_alert',
    // 'do_disturb_off',
    // 'phone_locked',
    // 'sim_card_alert',
    // 'airline_seat_flat_angled',
    // 'tv_off',
    // 'phone_bluetooth_speaker',
    // 'directions_off',
    // 'airline_seat_flat',
    // 'airline_seat_legroom_extra',
    // 'airline_seat_legroom_normal',
    // 'airline_seat_legroom_reduced',
    // 'keyboard_arrow_down',
    // 'phone_iphone',
    // 'smartphone',
    // 'keyboard_arrow_right',
    // 'computer',
    // 'security',
    // 'desktop_windows',
    // 'phone_android',
    // 'smart_display',
    // 'tv',
    // 'smart_toy',
    // 'keyboard_arrow_up',
    // 'keyboard_arrow_left',
    // 'keyboard_backspace',
    // 'headphones',
    // 'headset_mic',
    // 'keyboard',
    // 'laptop',
    // 'memory',
    // 'point_of_sale',
    // 'keyboard_return',
    // 'mouse',
    // 'keyboard_voice',
    // 'videogame_asset',
    // 'developer_board',
    // 'laptop_chromebook',
    // 'device_hub',
    // 'headset',
    // 'cast_for_education',
    // 'laptop_mac',
    // 'router',
    // 'cast',
    // 'watch',
    // 'monitor',
    // 'devices_other',
    // 'tablet_mac',
    // 'speaker',
    // 'desktop_mac',
    // 'phonelink',
    // 'keyboard_tab',
    // 'connected_tv',
    // 'toys',
    // 'keyboard_alt',
    // 'tablet_android',
    // 'gamepad',
    // 'cast_connected',
    // 'sim_card',
    // 'device_unknown',
    // 'laptop_windows',
    // 'headset_off',
    // 'scanner',
    // 'speaker_group',
    // 'keyboard_hide',
    // 'tablet',
    // 'earbuds',
    // 'keyboard_capslock',
    // 'home_max',
    // 'home_mini',
    // 'earbuds_battery',
    // 'headphones_battery',
    // 'smart_screen',
    // 'power_input',
    // 'browser_not_supported',
    // 'dock',
    // 'phonelink_off',
    // 'developer_board_off',
    // 'videogame_asset_off',
    // 'light_mode',
    // 'restart_alt',
    // 'dark_mode',
    // 'task',
    // 'password',
    // 'devices',
    // 'summarize',
    // 'sell',
    // 'settings_suggest',
    // 'quiz',
    // 'signal_cellular_alt',
    // 'thermostat',
    // 'widgets',
    // 'storage',
    // 'credit_score',
    // 'battery_full',
    // 'price_check',
    // 'gps_fixed',
    // 'medication',
    // 'pin',
    // 'battery_charging_full',
    // 'tungsten',
    // 'gpp_good',
    // 'price_change',
    // 'reviews',
    // 'air',
    // 'note_alt',
    // 'graphic_eq',
    // 'access_time',
    // 'bluetooth',
    // 'fmd_good',
    // 'water',
    // 'dvr',
    // 'sports_score',
    // 'nightlight',
    // 'share_location',
    // 'gpp_maybe',
    // 'bloodtype',
    // 'wifi_tethering',
    // 'airplane_ticket',
    // 'monitor_weight',
    // 'device_thermostat',
    // 'battery_std',
    // 'cable',
    // 'cameraswitch',
    // 'location_searching',
    // 'mode_night',
    // 'signal_wifi_4_bar',
    // 'radar',
    // 'data_usage',
    // 'shortcut',
    // 'lens_blur',
    // 'signal_cellular_4_bar',
    // 'wallpaper',
    // 'gpp_bad',
    // 'developer_mode',
    // 'network_wifi',
    // 'fmd_bad',
    // 'access_time_filled',
    // 'airplanemode_active',
    // 'signal_wifi_statusbar_4_bar',
    // 'screen_search_desktop',
    // 'splitscreen',
    // 'usb',
    // 'bluetooth_connected',
    // 'battery_alert',
    // 'flashlight_on',
    // 'send_to_mobile',
    // 'sim_card_download',
    // 'system_security_update_good',
    // 'nfc',
    // 'mobile_friendly',
    // 'remember_me',
    // 'gps_not_fixed',
    // 'storm',
    // 'screenshot',
    // 'mode_standby',
    // 'battery_saver',
    // 'signal_wifi_statusbar_connected_no_internet_4',
    // 'screen_rotation',
    // 'pattern',
    // 'data_saver_off',
    // 'play_lesson',
    // 'brightness_high',
    // 'network_cell',
    // 'grid_4x4',
    // 'bluetooth_searching',
    // 'brightness_low',
    // 'ad_units',
    // 'aod',
    // 'signal_wifi_0_bar',
    // 'data_saver_on',
    // 'mobiledata_off',
    // 'bluetooth_disabled',
    // 'security_update_good',
    // 'access_alarms',
    // 'hdr_auto',
    // 'brightness_medium',
    // 'security_update',
    // 'signal_wifi_bad',
    // 'signal_wifi_off',
    // 'battery_unknown',
    // 'wifi_lock',
    // 'settings_system_daydream',
    // 'wifi_calling_3',
    // '4g_mobiledata',
    // 'signal_cellular_0_bar',
    // 'flourescent',
    // 'sd_storage',
    // 'do_not_disturb_on_total_silence',
    // 'add_to_home_screen',
    // 'access_alarm',
    // 'gps_off',
    // 'signal_wifi_connected_no_internet_4',
    // 'grid_3x3',
    // 'brightness_auto',
    // 'wifi_tethering_error_rounded',
    // 'signal_wifi_statusbar_null',
    // '1x_mobiledata',
    // 'nearby_error',
    // 'screen_lock_portrait',
    // '30fps',
    // 'signal_wifi_4_bar_lock',
    // 'reset_tv',
    // '60fps',
    // 'flashlight_off',
    // 'lte_mobiledata',
    // 'security_update_warning',
    // 'media_bluetooth_on',
    // 'edgesensor_high',
    // 'signal_cellular_connected_no_internet_4_bar',
    // 'airplanemode_inactive',
    // 'bluetooth_drive',
    // '4g_plus_mobiledata',
    // 'add_alarm',
    // 'location_disabled',
    // 'wifi_tethering_off',
    // '3g_mobiledata',
    // 'system_security_update',
    // 'signal_cellular_off',
    // 'timer_10_select',
    // 'signal_cellular_connected_no_internet_0_bar',
    // 'system_security_update_warning',
    // 'signal_cellular_null',
    // 'edgesensor_low',
    // 'screen_lock_rotation',
    // 'timer_3_select',
    // 'mobile_off',
    // 'signal_cellular_nodata',
    // 'usb_off',
    // 'lte_plus_mobiledata',
    // 'rsvp',
    // 'grid_goldenratio',
    // 'screen_lock_landscape',
    // 'signal_cellular_no_sim',
    // 'g_mobiledata',
    // 'e_mobiledata',
    // 'media_bluetooth_off',
    // 'h_mobiledata',
    // 'r_mobiledata',
    // 'hdr_on_select',
    // 'hdr_auto_select',
    // 'hdr_off_select',
    // 'nearby_off',
    // 'h_plus_mobiledata',
    // 'storefront',
    // 'apartment',
    // 'fitness_center',
    // 'house',
    // 'spa',
    // 'business_center',
    // 'cottage',
    // 'meeting_room',
    // 'ac_unit',
    // 'corporate_fare',
    // 'family_restroom',
    // 'all_inclusive',
    // 'checkroom',
    // 'grass',
    // 'airport_shuttle',
    // 'other_houses',
    // 'child_care',
    // 'pool',
    // 'beach_access',
    // 'kitchen',
    // 'holiday_village',
    // 'casino',
    // 'roofing',
    // 'free_breakfast',
    // 'room_service',
    // 'gite',
    // 'sports_bar',
    // 'escalator_warning',
    // 'foundation',
    // 'room_preferences',
    // 'child_friendly',
    // 'villa',
    // 'food_bank',
    // 'bathtub',
    // 'night_shelter',
    // 'golf_course',
    // 'wash',
    // 'stairs',
    // 'backpack',
    // 'microwave',
    // 'smoking_rooms',
    // 'water_damage',
    // 'fire_extinguisher',
    // 'house_siding',
    // 'hot_tub',
    // 'countertops',
    // 'cabin',
    // 'baby_changing_station',
    // 'no_photography',
    // 'soap',
    // 'elevator',
    // 'wheelchair_pickup',
    // 'rv_hookup',
    // 'carpenter',
    // 'smoke_free',
    // 'tapas',
    // 'charging_station',
    // 'rice_bowl',
    // 'no_food',
    // 'fence',
    // 'umbrella',
    // 'balcony',
    // 'iron',
    // 'houseboat',
    // 'bento',
    // 'bungalow',
    // 'crib',
    // 'do_not_touch',
    // 'dry',
    // 'escalator',
    // 'chalet',
    // 'tty',
    // 'stroller',
    // 'do_not_step',
    // 'no_meeting_room',
    // 'no_drinks',
    // 'no_flash',
    // 'no_cell',
    // 'no_stroller',
    // 'no_backpack',
    // 'feed',
    // 'manage_search',
    // 'bed',
    // 'chair',
    // 'podcasts',
    // 'coffee',
    // 'shower',
    // 'yard',
    // 'light',
    // 'window',
    // 'door_front',
    // 'garage',
    // 'dining',
    // 'blender',
    // 'flatware',
    // 'bedroom_baby',
    // 'camera_indoor',
    // 'coffee_maker',
    // 'bedroom_parent',
    // 'bathroom',
    // 'door_sliding',
    // 'camera_outdoor',
    // 'chair_alt',
    // 'living',
    // 'doorbell',
    // 'bedroom_child',
    // 'door_back',
    'sensor_door',
    'sensor_window'
];