FROM node:16-alpine as builder
WORKDIR /app
RUN apk add openjdk17 git
COPY . .
RUN ./gradlew clean build

FROM amazoncorretto:17

USER 1000
WORKDIR /app

COPY --from=builder /app/build/libs/databucket-server-*.jar app.jar
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]